version: '3.4'

services:
  company.service.api:
    image: ${DOCKER_REGISTRY-}companyserviceapi
    build:
      context: .
      dockerfile: Company.Service.API/Dockerfile
  database:
    image: 'postgres:13.10-alpine'
    container_name: podtgres
    restart: always
  redis:  
    image: redis
  seq:
    image: 'datalust/seq:latest'
    container_name: seqlog
    restart: always
  user-db:
    image: ${DOCKER_REGISTRY-}companyservicedatabase
    build:
      context: DataBase/.
      dockerfile: Dockerfile
    container_name: user-db
    depends_on:
      database:
        condition: service_healthy
volumes:
  db-data:

