version: '3.4'

services:
  [%= company_lower %].[%= name_lower %]s.api:
    image: ${DOCKER_REGISTRY-}companyserviceapi
    build:
      context: .
      dockerfile: [%= company %].[%= name %]s.API/Dockerfile
  database:
    image: 'postgres:13.10-alpine'
    container_name: podtgres
    restart: always
  redis:  
    image: redis
  seq:
    image: 'datalust/seq:latest'
    container_name: seqlog
    restart: always
  [%= name_lower %]-db:
    image: ${DOCKER_REGISTRY-}[%= company_lower %][%= name_lower %]database
    build:
      context: DataBase/.
      dockerfile: Dockerfile
    container_name: [%= name_lower %]-db
    depends_on:
      database:
        condition: service_healthy
volumes:
  db-data:

